server:
  port: 8090
  forward-headers-strategy: native
  compression:
    enabled: true
  error:
    include-message: always
spring:
  profiles:
    active: ${PROFILE_ENV:dev}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 10240KB
      resolve-lazily: true
  flyway:
    enabled: false
  freemarker:
    suffix: .ftl
    settings:
      auto_import: /common/macro/global_macro.ftl as global
    template-loader-path:
      - file:///${halo.work-dir}/templates/
      - classpath:/templates/
    expose-spring-macro-helpers: false
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: [ 'httptrace', 'metrics', 'env', 'logfile', 'health' ]
