public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK63KAFdKDG0SawD0ayhGe9ZOgSq2sZVN6BDEfvRgxodNY5pzBzM1IpvlixP0SuBioguxpZB+eS4oiUpv5M1MacCAwEAAQ==
spring:
  devtools:
    restart:
      eanbled: true
  datasource:
    druid:
      username: root
      password: JvVNxaKrdehWw5Ppkctqb0vp3oWQTY7guQZmKAX0eKljb3nDmtLByfH4J1ig7hRt1aTgljc1Kqu6G91wwlIpyA==
      url: jdbc:mysql://127.0.0.1:3306/halo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,slf4j,config
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key};
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        allow:
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
logging:
  level:
    run.halo.app: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
  file:
    path: ${halo.work-dir}/logs
springfox:
  documentation:
    enabled: true
halo:
  auth-enabled: true
  mode: development
  workDir: ${user.home}/halo-dev/
  cache: memory