version: '3.4'

services:
  friday-nginx:
    image: nginx
    container_name: friday-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs:ro

  blog-mysql:
    image: mysql:5.7
    container_name: blog-mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./blog/mysql_data:/var/lib/mysql

  blog-halo:
    image: registry.cn-qingdao.aliyuncs.com/fridayplus/halo:0.2.10
    container_name: blog-halo
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      DB_HOST: blog-mysql
      PROFILE_ENV: prod
      MAX_UPLOAD_SIZE: 10m
      JVM_XMS: 256m
      JVM_XMX: 256m
    volumes:
      - ./blog/halo_backup:/tmp/halo-backup-markdown
      - ./blog/halo_data:/root/.halo
    links:
      - blog-mysql
    expose:
      - "8090"

networks:
  default:
    external:
      name: friday-network

